'use strict';
// 红队A 只读证据脚本 v2：走 p1b/src/deps 链（p10-w3-read-verdicts.cjs 同款）
const { db } = require("E:/music player/p1b/src/deps");
const dbPath = process.argv[2] || db.DEFAULT_DB_PATH;
console.log("DB_PATH=", dbPath);
db.init(dbPath);
const conn = db.getConnection();
const q = (sql) => conn.prepare(sql).all();
const one = (sql) => conn.prepare(sql).get();
const safe = (label, fn) => { try { console.log(label, fn()); } catch(e) { console.log(label, "ERR:", e.message); } };
safe("games_total=", () => one("SELECT COUNT(*) n FROM games").n);
safe("sim_games_count=", () => one("SELECT COUNT(*) n FROM games WHERE source='sim'").n);
safe("sim_gid_range=", () => q("SELECT id, name FROM games WHERE source='sim' ORDER BY id LIMIT 3"));
safe("sim_events=", () => one("SELECT COUNT(*) n FROM events e JOIN games g ON e.game_id=g.id WHERE g.source='sim'").n);
safe("sim_claims=", () => one("SELECT COUNT(*) n FROM claims c JOIN games g ON c.game_id=g.id WHERE g.source='sim'").n);
safe("pred_total=", () => one("SELECT COUNT(*) n FROM predictions").n);
safe("pred_by_source_type=", () => q("SELECT source_type, COUNT(*) n FROM predictions GROUP BY source_type"));
safe("pred_by_layer_outcome=", () => q("SELECT layer, outcome, COUNT(*) n FROM predictions GROUP BY layer, outcome ORDER BY layer, outcome"));
safe("pred_gid_range=", () => q("SELECT MIN(game_id) a, MAX(game_id) b FROM predictions")[0]);
safe("pred_prob_05=", () => one("SELECT COUNT(*) n FROM predictions WHERE assigned_prob=0.5").n);
safe("pred_prob_null=", () => one("SELECT COUNT(*) n FROM predictions WHERE assigned_prob IS NULL").n);
safe("pred_layer_null=", () => one("SELECT COUNT(*) n FROM predictions WHERE layer IS NULL").n);
safe("pred_dup_", () => one("SELECT COUNT(*) n FROM (SELECT game_id, statement, COUNT(*) c FROM predictions GROUP BY game_id, statement HAVING c>1)").n);
safe("verdicts_total=", () => one("SELECT COUNT(*) n FROM verdicts").n);
safe("verdicts_by_variant=", () => q("SELECT prompt_variant, temperature, COUNT(*) n, SUM(implied_prob IS NULL) nulls FROM verdicts GROUP BY prompt_variant, temperature"));
safe("verdicts_distinct_pid=", () => one("SELECT COUNT(DISTINCT prediction_id) n FROM verdicts").n);
db.closeCurrent();
