'use strict';
const Database = require('E:/music player/p1a-terminal/node_modules/better-sqlite3');
const db = new Database('E:/music player/p1a-terminal/data/p1a.db', { readonly: true });
const one = (s) => db.prepare(s).get();
const all = (s) => db.prepare(s).all();
console.log('--- id=473 full evidence ---');
console.log(one('SELECT evidence_json FROM predictions WHERE id=473').evidence_json);
console.log('--- id=1497 evidence ---');
const r1497 = one('SELECT id, checklist_hash, outcome, substr(evidence_json,1,400) ej FROM predictions WHERE id=1497');
console.log(JSON.stringify(r1497, null, 1));
console.log('--- BETWEEN but not absdev (the 39) ---');
console.log(JSON.stringify(all('SELECT assigned_prob, COUNT(*) n FROM predictions WHERE assigned_prob BETWEEN 0.35 AND 0.65 AND ABS(assigned_prob-0.5)>0.15 GROUP BY assigned_prob'), null, 1));
console.log('--- sqlite_master all objects ---');
console.log(JSON.stringify(all("SELECT type, name FROM sqlite_master WHERE type IN ('table','view','trigger') ORDER BY type,name"), null, 1));
console.log('--- games.source dist ---');
console.log(JSON.stringify(all('SELECT source, COUNT(*) n FROM games GROUP BY source'), null, 1));
console.log('--- unresolved without resolve key ---');
console.log(JSON.stringify(one("SELECT COUNT(*) n FROM predictions WHERE outcome IS NULL AND NOT EXISTS (SELECT 1 FROM json_each(predictions.evidence_json) e WHERE json_extract(e.value,'$.resolve') IS NOT NULL)"), null, 1));
console.log('--- 450 instant-resolve: checklist/layer ---');
console.log(JSON.stringify(all("SELECT COALESCE(checklist_hash,'NULL') ch, COALESCE(layer,'NULL') l, COUNT(*) n FROM predictions WHERE created_at=resolved_at GROUP BY ch,l"), null, 1));
console.log('--- per-layer hard share (|p-.5|<=.15, over rows with prob) ---');
console.log(JSON.stringify(all("SELECT layer, COUNT(*) n, SUM(CASE WHEN ABS(assigned_prob-0.5)<=0.15 THEN 1 ELSE 0 END) hard FROM predictions WHERE assigned_prob IS NOT NULL GROUP BY layer"), null, 1));
console.log('--- truth_preview sample values ---');
console.log(JSON.stringify(all("SELECT id, outcome, json_extract(e.value,'$.truth_preview') tp FROM predictions p, json_each(p.evidence_json) e WHERE json_extract(e.value,'$.truth_preview') IS NOT NULL LIMIT 5"), null, 1));
db.close();
