'use strict';
const Database = require('E:/music player/p1a-terminal/node_modules/better-sqlite3');
const db = new Database('E:/music player/p1a-terminal/data/p1a.db', { readonly: true });
const one = (s) => db.prepare(s).get();
const all = (s) => db.prepare(s).all();
const out = {};
out.games = one('SELECT COUNT(*) n FROM games').n;
out.predictions = one('SELECT COUNT(*) n FROM predictions').n;
out.resolved_outcome = one('SELECT COUNT(*) n FROM predictions WHERE outcome IS NOT NULL').n;
out.unresolved = one('SELECT COUNT(*) n FROM predictions WHERE outcome IS NULL').n;
out.checklist_null = one('SELECT COUNT(*) n FROM predictions WHERE checklist_hash IS NULL').n;
out.secondary_nonnull = one('SELECT COUNT(*) n FROM predictions WHERE secondary_layer IS NOT NULL').n;
out.truth_preview = one("SELECT COUNT(*) n FROM predictions WHERE evidence_json LIKE '%truth_preview%'").n;
out.created_eq_resolved = one('SELECT COUNT(*) n FROM predictions WHERE created_at = resolved_at').n;
out.resolved_no_resolve_key = one("SELECT COUNT(*) n FROM predictions WHERE outcome IS NOT NULL AND NOT EXISTS (SELECT 1 FROM json_each(predictions.evidence_json) e WHERE json_extract(e.value,'$.resolve') IS NOT NULL)").n;
out.between_035_065 = one('SELECT COUNT(*) n FROM predictions WHERE assigned_prob BETWEEN 0.35 AND 0.65').n;
out.absdev_le_015 = one('SELECT COUNT(*) n FROM predictions WHERE assigned_prob IS NOT NULL AND ABS(assigned_prob-0.5)<=0.15').n;
out.p035 = one('SELECT COUNT(*) n FROM predictions WHERE assigned_prob=0.35').n;
out.p065 = one('SELECT COUNT(*) n FROM predictions WHERE assigned_prob=0.65').n;
out.pred_cols = all('PRAGMA table_info(predictions)').length;
out.tables = all("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").map(r=>r.name);
out.games_cols = all('PRAGMA table_info(games)').map(r=>r.name);
out.layer_dist = all('SELECT layer, COUNT(*) n FROM predictions GROUP BY layer ORDER BY layer');
out.ch_group = all("SELECT COALESCE(checklist_hash,'NULL') ch, COUNT(*) n, SUM(outcome IS NOT NULL) r FROM predictions GROUP BY checklist_hash ORDER BY n DESC");
console.log(JSON.stringify(out, null, 1));
console.log('--- evidence.kind x checklist_hash ---');
console.log(JSON.stringify(all("SELECT json_extract(e.value,'$.kind') k, COALESCE(p.checklist_hash,'NULL') ch, COUNT(*) n FROM predictions p, json_each(p.evidence_json) e WHERE json_extract(e.value,'$.kind') IS NOT NULL GROUP BY k,ch ORDER BY n DESC"), null, 1));
console.log('--- id=473 ---');
console.log(JSON.stringify(one('SELECT id, outcome, checklist_hash, substr(evidence_json,1,300) ej FROM predictions WHERE id=473'), null, 1));
db.close();
